"""增加数据库中多对多关系

Revision ID: 558743fdaaaa
Revises: 67e5122cdcc3
Create Date: 2024-10-31 17:18:08.237259

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '558743fdaaaa'
down_revision = '67e5122cdcc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_cover_path', sa.String(length=255), nullable=True))

    with op.batch_alter_table('downloads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_image_path', sa.String(length=255), nullable=True))
        batch_op.drop_constraint('songs_ibfk_1', type_='foreignkey')
        batch_op.drop_column('artist_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('songs_ibfk_1', 'artists', ['artist_id'], ['id'])
        batch_op.drop_column('local_image_path')

    with op.batch_alter_table('downloads', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.drop_column('local_cover_path')

    op.create_table('comments',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='comments_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
