"""songs字段更新

Revision ID: 8878dd31db3a
Revises: aa879986a15b
Create Date: 2024-11-03 15:56:33.374994

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8878dd31db3a'
down_revision = 'aa879986a15b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.drop_column('artist_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist_id', mysql.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
