"""新增歌曲我喜欢字段

Revision ID: 9a151e25287f
Revises: 8878dd31db3a
Create Date: 2024-11-12 19:43:46.399153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a151e25287f'
down_revision = '8878dd31db3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.drop_column('likes_count')

    # ### end Alembic commands ###
